from app.models.user import User
from app.models.admin import Admin
from app.models.airplane import Airplane
from app.models.seat import Seat
from app.models.flight import Flight
from app.models.ticket import Ticket
from app.models.flight_log import FlightLog
from app.models.booked_tickets import BookedTicket
from app.models.general_info import GeneralInfo
from app.models.promotions import Promotion
from app.models.news import News
from app.models.notifications import Notification
