from .flights import router as flights_router
from .bookings import router as bookings_router
from .users import router as users_router
from .general_info import router as general_info_router
from .airports import router as airports_router
from .bookings import router as bookings_router
from .seats import router as seats_router
from .news import router as news_router
from .notifications import router as notification_router
from .promotions import router as promotion_router
from .tickets import router as tickets_router
from .flight_logs import router as flight_log_router
from .admin import router as admin_router
from .airplanes import router as airplane_router
from .login_auth import router as login_auth_router
