"""Initial migration

Revision ID: 020fa0e64d85
Revises: 
Create Date: 2024-11-24 15:51:25.039822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020fa0e64d85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airplanes',
    sa.Column('airplane_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('seat_capacity', sa.Integer(), nullable=False),
    sa.Column('range_km', sa.Integer(), nullable=True),
    sa.Column('year_of_manufacture', sa.Integer(), nullable=True),
    sa.Column('maintenance_status', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('airplane_id')
    )
    op.create_index(op.f('ix_airplanes_airplane_id'), 'airplanes', ['airplane_id'], unique=False)
    op.create_table('general_info',
    sa.Column('info_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('info_id')
    )
    op.create_index(op.f('ix_general_info_info_id'), 'general_info', ['info_id'], unique=False)
    op.create_table('promotions',
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('promotion_id')
    )
    op.create_index(op.f('ix_promotions_promotion_id'), 'promotions', ['promotion_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_index(op.f('ix_admins_admin_id'), 'admins', ['admin_id'], unique=False)
    op.create_table('flights',
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('airplane_id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('departure_airport', sa.String(length=100), nullable=False),
    sa.Column('arrival_airport', sa.String(length=100), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('flight_duration', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('available_seats', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['airplane_id'], ['airplanes.airplane_id'], ),
    sa.PrimaryKeyConstraint('flight_id'),
    sa.UniqueConstraint('flight_number')
    )
    op.create_index(op.f('ix_flights_flight_id'), 'flights', ['flight_id'], unique=False)
    op.create_table('seats',
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('airplane_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.String(length=10), nullable=False),
    sa.Column('seat_class', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['airplane_id'], ['airplanes.airplane_id'], ),
    sa.PrimaryKeyConstraint('seat_id')
    )
    op.create_index(op.f('ix_seats_seat_id'), 'seats', ['seat_id'], unique=False)
    op.create_table('flight_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('log_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_flight_logs_log_id'), 'flight_logs', ['log_id'], unique=False)
    op.create_table('news',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['admins.admin_id'], ),
    sa.PrimaryKeyConstraint('news_id')
    )
    op.create_index(op.f('ix_news_news_id'), 'news', ['news_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    op.create_table('tickets',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('class_type', sa.String(length=50), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_tickets_ticket_id'), 'tickets', ['ticket_id'], unique=False)
    op.create_table('booked_tickets',
    sa.Column('booked_ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('booking_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.seat_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('booked_ticket_id')
    )
    op.create_index(op.f('ix_booked_tickets_booked_ticket_id'), 'booked_tickets', ['booked_ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booked_tickets_booked_ticket_id'), table_name='booked_tickets')
    op.drop_table('booked_tickets')
    op.drop_index(op.f('ix_tickets_ticket_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_news_news_id'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_flight_logs_log_id'), table_name='flight_logs')
    op.drop_table('flight_logs')
    op.drop_index(op.f('ix_seats_seat_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_flights_flight_id'), table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_admins_admin_id'), table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_promotions_promotion_id'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_general_info_info_id'), table_name='general_info')
    op.drop_table('general_info')
    op.drop_index(op.f('ix_airplanes_airplane_id'), table_name='airplanes')
    op.drop_table('airplanes')
    # ### end Alembic commands ###
