"""Delete publish_dated from news

Revision ID: 30f593d96671
Revises: 4c2999b7734d
Create Date: 2024-11-28 00:46:12.689033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '30f593d96671'
down_revision: Union[str, None] = '4c2999b7734d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'published_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('published_date', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
