"""add new columns

Revision ID: 4f7a38f8239a
Revises: 30f593d96671
Create Date: 2024-12-18 22:40:26.457045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4f7a38f8239a'
down_revision: Union[str, None] = '30f593d96671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('location_id', table_name='locations')
    op.drop_table('locations')
    op.add_column('airports', sa.Column('general_info', sa.String(length=1000), nullable=True))
    op.add_column('airports', sa.Column('check_in_counters', sa.String(length=500), nullable=True))
    op.add_column('airports', sa.Column('shopping_services', sa.String(length=500), nullable=True))
    op.add_column('airports', sa.Column('lounge_services', sa.String(length=500), nullable=True))
    op.add_column('airports', sa.Column('food_services', sa.String(length=500), nullable=True))
    op.add_column('airports', sa.Column('currency_exchange', sa.String(length=500), nullable=True))
    op.alter_column('booked_tickets', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booked_tickets', 'price',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('airports', 'currency_exchange')
    op.drop_column('airports', 'food_services')
    op.drop_column('airports', 'lounge_services')
    op.drop_column('airports', 'shopping_services')
    op.drop_column('airports', 'check_in_counters')
    op.drop_column('airports', 'general_info')
    op.create_table('locations',
    sa.Column('location_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('screen', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('food', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('activity', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('experience', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('airport_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.airport_id'], name='locations_ibfk_1'),
    sa.PrimaryKeyConstraint('city'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('location_id', 'locations', ['location_id'], unique=True)
    # ### end Alembic commands ###
