"""Update database structure

Revision ID: 542bad0d0811
Revises: 020fa0e64d85
Create Date: 2024-11-24 16:04:43.634806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '542bad0d0811'
down_revision: Union[str, None] = '020fa0e64d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('admins', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'admins', ['username'])
    op.drop_constraint('admins_ibfk_1', 'admins', type_='foreignkey')
    op.drop_column('admins', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('admins_ibfk_1', 'admins', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_column('admins', 'hashed_password')
    op.drop_column('admins', 'username')
    # ### end Alembic commands ###
