"""Add airport model and update flight relationships

Revision ID: 97ad43fcabbc
Revises: fd7dfa8e585d
Create Date: 2024-11-25 22:05:15.737613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '97ad43fcabbc'
down_revision: Union[str, None] = 'fd7dfa8e585d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('departure_airport_id', sa.Integer(), nullable=False))
    op.add_column('flights', sa.Column('arrival_airport_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'flights', 'airports', ['arrival_airport_id'], ['airport_id'])
    op.create_foreign_key(None, 'flights', 'airports', ['departure_airport_id'], ['airport_id'])
    op.drop_column('flights', 'arrival_airport')
    op.drop_column('flights', 'departure_airport')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('departure_airport', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('flights', sa.Column('arrival_airport', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_column('flights', 'arrival_airport_id')
    op.drop_column('flights', 'departure_airport_id')
    # ### end Alembic commands ###
