"""Update user

Revision ID: cd887a88723a
Revises: e4a4ece8b89c
Create Date: 2024-12-20 09:35:09.836435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd887a88723a'
down_revision: Union[str, None] = 'e4a4ece8b89c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('location_id', table_name='locations')
    op.drop_table('locations')
    op.alter_column('users', 'date_of_birth',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.String(length=20),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.create_table('locations',
    sa.Column('location_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('screen', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('food', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('activity', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('experience', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('airport_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.airport_id'], name='locations_ibfk_1'),
    sa.PrimaryKeyConstraint('city'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('location_id', 'locations', ['location_id'], unique=True)
    # ### end Alembic commands ###
