"""Update user

Revision ID: e4a4ece8b89c
Revises: 242293e35a8e
Create Date: 2024-12-20 09:15:44.138418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4a4ece8b89c'
down_revision: Union[str, None] = '242293e35a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('location_id', table_name='locations')
    op.drop_table('locations')
    op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'address')
    op.create_table('locations',
    sa.Column('location_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('screen', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('food', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('activity', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('experience', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('airport_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.airport_id'], name='locations_ibfk_1'),
    sa.PrimaryKeyConstraint('city'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('location_id', 'locations', ['location_id'], unique=True)
    # ### end Alembic commands ###
