"""Update foreign keys

Revision ID: f494cb138ae4
Revises: 7af0f4219ed4
Create Date: 2024-11-24 16:56:42.426143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f494cb138ae4'
down_revision: Union[str, None] = '7af0f4219ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('seat_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tickets', 'seats', ['seat_id'], ['seat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'seat_id')
    # ### end Alembic commands ###
